f(try g())

try:
  something()
catch:
  noErrArg()
