a = b()
  catch Error as err: err
